### PR TITLE
Add cap-value batch type

### LINKED ISSUE #167: cap-notify-3.2 specifies a vendor-prefixed batch called "example.com/cap-value"
@attilamolnar 

>03:23 < dx> what's up with that "BATCH +cap example.com/cap-value" in http://ircv3.net/specs/extensions/cap-notify-3.2.html
>03:28 < Aerdan> sending both CAP commands as a single transaction.
>03:29 < dx> i mean the example.com/ vendor prefix specifically. seems like it's defining a new batch type and simultaneously making it unusable
>03:30 < Aerdan> ask attila.
>03:30 < dx> hm. i guess the only way to ask attila is through the issue tracker?
>03:31 < dx> he's alive there
>03:32 < DarthGandalf> That can be made a proper batch type, if useful
>03:32 < DarthGandalf> without prefix

### PR DESCRIPTION
**Pull request by DarthGandalf**
Fix #167

### CODE REVIEW

**Comment by kaniini** [comment]
:+1:

**Comment by jwheare** [comment]
Might be worth discussing whether CAP NEW could be upgraded to work as a CAP UPDATE to avoid the need for this entirely?

**Comment by jwheare** [comment]
Given this disables the CAP on the client either way, what problem does this solve?

**Comment by DarthGandalf** [comment]
This was so long ago...
AFAIR, this is to prevent client from forgetting about certain caps in case
of a power failure.
E.g. if server changes duration of `sts`, it disables DELs it, then NEWs it
with another value. Client might assume that deleting the cap is a signal
that SSL shouldn't to be used anymore. Usually client will receive CAP NEW
after that, and will know again to use SSL, but not in case of
power/network failure.

2016-12-21 17:17 GMT+00:00 James Wheare <notifications@github.com>:

**Comment by jwheare** [comment]
OK. Seems extremely edge case-ish to me. If I understand correctly, in case of a power failure, the connection will close and sts will be renegotiated on the next connection attempt, so is this a real issue? I may be missing something.

**Comment by DarthGandalf** [comment]
Yes, except that the next connection attempt will be without SSL.
Yes, it's a very edge case.

Maybe some other caps can be affected by something similar, not only `sts`.

2016-12-28 10:20 GMT+00:00 James Wheare <notifications@github.com>:

**Comment by attilamolnar** [comment]
> E.g. if server changes duration of `sts`, it disables DELs it, then NEWs it with another value. Client might assume that deleting the cap is a signal that SSL shouldn't to be used anymore. Usually client will receive CAP NEW after that, and will know again to use SSL, but not in case of power/network failure.

That's a wrong assumption for clients to make. sts is disabled by setting the duration to 0, not via CAP DEL. CAP DEL for sts should have no effect on the established policy.

**Comment by jwheare** [comment]
In the absence of a compelling use case, we should probably close this and reopen if needed.

**Pull request closed without merging**
