### PR TITLE
sasl-3.1: add SCRAM and mention that the client must always send a response

### PR DESCRIPTION
**Pull request by grawity**

### CODE REVIEW

**Comment by jwheare** [comment]
Thanks LGTM. This resolves #325. Holding off on merging until I've reviewed your other edits here https://github.com/grawity/ircv3-specifications/blob/sasl2/extensions/sasl-3.1.md

**Comment by jwheare** [comment]
I added some commit comments on the further edits here: https://github.com/grawity/ircv3-specifications/commit/317c2fad89973f17f955c41df62632da0914095f

**Comment by jwheare** [comment]
@grawity any thoughts on the review comments?

**Comment by grawity** [comment]
The full rewrite is not part of this PR, not sure why it's a blocker...

**Comment by jwheare** [comment]
Fair enough. Could you open a WIP PR for those edits then?

**Pull request merged**
