### PR TITLE
Spec cleanups

### PR DESCRIPTION
**Pull request by DanielOaks**
This PR does steps 2+3+4 in #329 - cleans up the specs, puts them in a more defined folder structure, and unifies the titles (both how they're named, and also removing useless duplicated Markdown titles).

I've left Metadata and SASL alone for now, since there's some non-trivial PRs to those.

### CODE REVIEW

**Review by ProgVal — COMMENTED** [review]
> Fix duplicate markdown headers.

Shouldn't you add a new header at the beginning, eg. `## Description` for consistency with https://ircv3.net/specs/extensions/echo-message-3.2.html ?

>  Reorganise specs under new folder structure. 

Shouldn't they all have a redirect?

**Comment by DanielOaks** [comment]
re markdown headers I was thinking that yeah, `## Description` or `## Introduction` or whatever fits - will need to see what fits for each spec. Will throw another commit on top adding them, thanks for the yell.

Yeah I've added redirects from their old locations to their new ones, `redirect_from` key in the yaml header auto-creates redirect files.

**Comment by DanielOaks** [comment]
Cool, I'm fairly happy with this now. Some of these changes are made for the sake of consistency across our specs, but I've tried to only touch the initial header terms / metadata / file structure and no actual spec text here. Good step forward, not the last, keep an eye on #329 for future work I plan to do on our existing specs, and throw additional suggestions in there. Reviews + merge pls.

**Comment by jwheare** [comment]
Looking snazzy. Can you make a draft pr to the website repo that refs this branch for the submod so we can preview it?

**Comment by DanielOaks** [comment]
Draft website view: https://deploy-preview-355--ircv3.netlify.app/irc/

**Comment by DanielOaks** [comment]
So I'd like SNI, and future stuff like the [clients loading urls considerations document](https://github.com/ircv3/ircv3-ideas/issues/16) to live outside of `https://ircv3.net/specs/` since they... don't really fit there, I reckon. More appropriate under a different root folder on the site, say `https://ircv3.net/docs/*` instead. So I've taken that document out of this repo, and I'll throw it into the website repo when these changes get merged. Down the line, once we have more than like, one or two documents, we could have a generic repo for docs vs specifications, but that's work that can be really easily done in future given the very few documents along these lines that we have right now.

**Comment by jwheare** [comment]
Is this good to go?

**Pull request merged**
