### PR TITLE
Update echo-message to require servers to echo TAGMSGs as well.

### PR DESCRIPTION
**Pull request by SaberUK**

### CODE REVIEW

**Comment by DanielOaks** [comment]
Yeah I think this makes sense to do (of course, so long as the client being replayed to has the `message-tags` capability negotiated). `TAGMSG` is basically the same as PRIVMSG and NOTICE for intents and purposes here, and considering only new clients will get this behaviour there's no worries.

Should we add a quick mention about needing the `message-tags` capability to be negotiated? We should definitely add an errata item noting the change. Nice PR~

**Comment by jwheare** [comment]
This needs to be clarified in the message-tags spec primarily.

**Comment by jwheare** [comment]
Oh, this is already mentioned in message-tags:

> This means for example, honouring channel membership, modes, echo-message, …

**Comment by jwheare** [comment]
Echo message change added in #373. This isn't really an errata, more new information from another spec.

**Pull request closed without merging**
