### PR TITLE
Modified echo-message for 3.2

### PR DESCRIPTION
**Pull request by kaniini**
This pull request provides a modified `echo-message` capability for 3.2.  The modification removes the example which takes advantage of 3.3's labeled replies proposal.

Closes #100, #135.

### CODE REVIEW

**Comment by jpnurmi** [comment]
:+1:

**Comment by kaniini** [comment]
What language would you prefer?

**Comment by dequis** [comment]
Since I needed a diff to realize what was removed in this version, including it here for the record (it's just the last paragraph/example)

```diff
--- extensions/echo-message-3.3.md
+++ extensions/echo-message-3.2.md
@@ -54,10 +54,3 @@
 
     --> PRIVMSG #ircv3 :back from \02lunch\0F
     :example!ex@example.com PRIVMSG #ircv3 :back from lunch
-
-A client may add an `id` tag to correlate between sent messages and
-echoed ones (which might have been modified by the server). If an `id`
-tag is present, the server must echo it.
-
-    --> @id=cd87d2 NOTICE jpnurmi :important note
-    @id=cd87d2 :example!ex@example.com NOTICE jpnurmi :important note
```

**Comment by kaniini** [comment]
@dequis The example removed depends on 3.3's labelled replies.

**Comment by kaniini** [comment]
I propose replacing the entire paragraph with:

> If enabled, servers MUST send `PRIVMSG` and `NOTICE` reply with the
> message that was sent after applying any relevant modifications to
> the message.

I believe this, in combination with the following paragraph, resolve the concern with bouncers, since bouncers are required to treat it as a client message, which to me, would mean redistribute it to the other clients which support `echo-message`.

@grawity @jpnurmi thoughts?

**Comment by jpnurmi** [comment]
I like the simplified version of the paragraph. I don't mind having some additional bouncer specific mentions to clarify things, but the motivation of this capability was to replace self-message with something that is not so specific to bouncers. :)

**Comment by DarthGandalf** [comment]
self-message spec needs to be deleted then?
If server is allowed to send modified line back, it makes it harder for client to show line in pending state, because it can't know if received line is the sent line or not. It should be addressed by labelled-replies later though.

**Comment by kaniini** [comment]
@DarthGandalf @grawity already deleted the broken `self-message` one.  this is the "replace" part of our repeal and replace strategy ;)

**Pull request merged**
