### PR TITLE
Add a template for specifications to follow.

### PR DESCRIPTION
**Pull request by SaberUK**
This is just an initial draft. Feedback would be appreciated.

### CODE REVIEW

**Comment by dequis** [comment]
Sections for numerics, capabilities, and isupport tokens?

And i think it'd be better to remove those sections if they are empty instead of having "This specification defines no client commands."

Also the template might get too verbose with all of those, i'd say just put them one per line, like

```
### Server Commands
### Client Commands
### Channel Modes
### User Modes
### Numerics
### Capabilities
### ISUPPORT tokens
```

And tell people to remove or fill as needed.

**Comment by DanielOaks** [comment]
:+1:

I agree with @dequis as well, those sections seem like ones that can be omitted if they're not required.

**Comment by SaberUK** [comment]
@dequis Done!

**Comment by jwheare** [comment]
As of yesterday (https://github.com/blog/2111-issue-and-pull-request-templates) we can name this file `.github/PULL_REQUEST_TEMPLATE.md` for added magic.

**Comment by SaberUK** [comment]
This is a template for specifications not for pull requests though.

**Comment by jwheare** [comment]
Ah true, never mind.

**Comment by SaberUK** [comment]
I don't think there are any more comments on this. Can it be merged now?

**Comment by jwheare** [comment]
The following sections should be optional: Security implications, Alternatives, Errata. For new specifications, there won't ever be errata, so it's a bit redundant to include it at all in the template.

**Comment by attilamolnar** [comment]
I don't think this should be merged like this. Empty/placeholder sections aren't needed in specifications. No IRCv3 specifications add user or channel modes. Why reserve a section for them?

**Pull request closed without merging**
