### PR TITLE
Rewrite METADATA LIST

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by DarthGandalf** [comment]
Though, probably 2 different commands would be better for this.

**Comment by kaniini** [comment]
Perhaps `METADATA GET`? :)

**Comment by DarthGandalf** [comment]
Almost made it SHOW. But now changed it to GET, ok...

**Comment by kaniini** [comment]
`GET` is definitely the right verb to use here, it fits in with other protocols too (HTTP GET for example).

Otherwise it looks okay.  :+1: from me.

**Comment by Aerdan** [comment]
Personally, I feel it should be `GET` → `SEARCH`, `LIST` → `GET`, if we're splitting functionality off of `LIST` like this.

**Comment by DarthGandalf** [comment]
`GET` is counterpart for `SET`, and `SET` works with only 1 key.

**Pull request merged**
