### PR TITLE
Add a basic readme

### PR DESCRIPTION
**Pull request by DanielOaks**
Points users to our site, etc. See #216

### CODE REVIEW

**Comment by jwheare** [comment]
Yay. Maybe also add links to http://ircv3.net/charter.html and http://ircv3.net/conduct.html (perhaps on CONTRIBUTING.md)

And a link to IRC would be good too ircs://irc.freenode.net:6697/#ircv3

**Comment by DanielOaks** [comment]
Github doesn't like any links that aren't http/s, so I think that link works for now. We can always direct them to our contact page otherwise, though. Yeah I could throw conduct link into CONTRIBUTING, along with some other suggested changes/fixes for it.

**Comment by ChickenNuggers** [comment]
i've heard talk about adding an FAQ; perhaps here would be a good place for just a few questions.

**Comment by DanielOaks** [comment]
I'd probably chuck that onto the site instead. The main point of the readme is just to direct people to the site when they stumble onto the git repo.

**Comment by dequis** [comment]
Anything pending with this or can it be merged?

**Comment by jwheare** [comment]
Freenode -> freenode

Also change the charter link to say something like:

> To read more about why IRCv3 exists and how it operates, see the [working group charter](http://ircv3.net/charter.html).

**Comment by attilamolnar** [comment]
LGTM

**Pull request merged**
