### PR TITLE
Add draft/no-implicit-names

### PR DESCRIPTION
**Pull request by emersion**
This has been deployed on soju and goguma.

See benchmarks in https://github.com/ircv3/ircv3-ideas/issues/87#issuecomment-1066766062.

Last week I was in the countryside with only 3G access and this was useful.

### CODE REVIEW

**Comment by progval** [comment]
Added to Matrix2051: https://github.com/progval/matrix2051/commit/5a92f46f28589aecc812f30e3e17468498d76e4e

Limnoria probably won't implement it despite always sending `WHO` after joining, because I worry about the side-effects of getting user lists delayed, especially in third-party plugins.

**Comment by slingamn** [comment]
Merged in Ergo: https://github.com/ergochat/ergo/pull/2083

**Comment by ValwareIRC** [comment]
I've never made a bot which needed to know who was in the channel yet, this sounds like a good idea to me

**Comment by SadieCat** [comment]
I've implemented this. It's available on the InspIRCd Testnet now.

**Review by jesopo — APPROVED** [review]
i do hope that in the future we'll have more generalised ways of expressing which bits of data a client wants, but in the meantime i have no opposition to this draft

**Review by ValwareIRC — APPROVED** [review]

**Comment by jwheare** [comment]
Good to merge?

**Pull request merged**
