### PR TITLE
Cleanup and unify specs for the website

### PR DESCRIPTION
**Pull request by DanielOaks**
So, this is a big PR, and it changes lots of stuff.

Basically, this is what I wanna change so that everything works nicely for the website.

1. `specifications` is renamed to `core` so it works more nicely with web paths
2. `.md` is added to all spec documents (so markdown renders properly into pages)
3. YAML front-matter is added to all markdown documents so they render properly
4. Titles and other formatting are unified so that they're consistent between all the documents

### CODE REVIEW

**Comment by kaniini** [comment]
Can we see a render of it?

**Comment by DanielOaks** [comment]
Yep, here's the [repo](https://github.com/DanielOaks/ircv3-specs-web-2) (with my website-cleanup branch submodule'd), and the [website](http://danieloaks.net/ircv3-specs-web-2/).

**Comment by kaniini** [comment]
:+1:

**Comment by kaniini** [comment]
All of this seems fine.  Can someone get this merged?

**Pull request merged**
