### PR TITLE
Ratify Message IDs

### PR DESCRIPTION
**Pull request by DanielOaks**
I reckon we've shown this to be stable enough, we have a few server implementations and all. Should be right to ratify as-is it feels like?

### CODE REVIEW

**Comment by jwheare** [comment]
Might be worth some further thought around whether we suggest encoding account ids in msgids to allow for eg certain editing proposals https://github.com/ircv3/ircv3-specifications/pull/304#issuecomment-464101264

**Comment by DanielOaks** [comment]
Definitely an interesting idea. Message editing/deletion is an interesting case in particular (imo seems a lot more suited to server-side checking of those kinds of things than doing it client-side), but in general I'm on the side of preserving the opacity of the message IDs.

**Comment by slingamn** [comment]
IMO the essential features of `draft/msgid` are:

1. The server has freedom to generate arbitrary IDs as long as they are unique-per-network and "sane" (not ridiculously long? no weird bytes?)
1. The IDs are completely opaque from the client's perspective (the client is only allowed to compare them for uniqueness)

Server implementations should be free to use uuidv4s (pure randomness), or stuff trusted data in them protected by an AEAD (as in the editmsg proposal), or whatever --- the client shouldn't care. I think embedding a client-server protocol inside msgid is very much out of scope.

**Comment by SaberUK** [comment]
If there's no more objections can we ratify this?

**Comment by jwheare** [comment]
Not really an objection, I just still think it's worth mentioning explicitly that while ids are to always be treated as opaque by clients, servers might wish to encode specific information in them that they can reuse for authenticated actions like edits/deletes.

**Comment by DanielOaks** [comment]
Have considered other suggested text from @slingamn. While I like the gist of it and that middle sentence feels cool, it feels like it removes a bit too much context on this 'may' at all. I'm leaving that PR as-is since... it works fine, and feels reasonable. Esp for a single-para 'maybe'. No other changes made to it in this PR.

**Comment by slingamn** [comment]
My proposal for a compromise wording:

>Servers might wish to encode additional information within the ID, for internal use only. For instance, including account information for the author in an ID could enable authenticated message edits or deletes, without having to maintain and consult a separate message store. This requires careful attention to several concerns: security, privacy, and backwards and forwards compatibility of different ID generation schemes.

**Comment by jwheare** [comment]
@slingamn yup that works for me

**Comment by jwheare** [comment]
LGTM, happy to merge

**Comment by jwheare** [comment]
Will do so tomorrow if no other comments. I strongly recommend reading the whole spec again, not just this changeset.

**Comment by jwheare** [comment]
This was published to the website in https://github.com/ircv3/ircv3.github.io/commit/0d5ed78b5b73eca4d00938cca6155d1570f63255

**Comment by jwheare** [comment]
This was published to the website in https://github.com/ircv3/ircv3.github.io/pull/252

**Pull request merged**
